---
name: Template-Provider-FromDATA
version: 0.05
author:
  - 'Brian Cassidy <bricas@cpan.org>'
abstract: Load templates from your __DATA__ section
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Template: 2.15
provides:
  Template::Provider::FromDATA:
    file: lib/Template/Provider/FromDATA.pm
    version: 0.05
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
